project:
  type: website
  output-dir: docs

website:
  title: "Jovan's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - fyp.qmd
      - data_visualization.qmd
      - reflection.qmd

format:
  html:
    theme:
      - pulse
    css: styles.css
    toc: true



